# 100 numpy exercises

The goal is both to offer a quick reference for new and old users and to
provide also a set of exercices for those who teach. If you remember
having asked or answered a (short) problem, you can send a pull request.
The format is:


Here is what the page looks like so far:
<http://www.loria.fr/~rougier/teaching/numpy.100/index.html>


# Note

The level names came from an old-game (Dungeon Master)


Repository is at: <https://github.com/rougier/numpy-100>


The corresponding [IPython
notebook](https://github.com/rougier/numpy-100/blob/master/README.ipynb)
is available from the github repo, thanks to the
[rst2ipynb](https://github.com/esc/rst2ipynb) conversion tool by
[Valentin Haenel](http://haenel.co)


Thanks to Michiaki Ariga, there is now a [Julia
version](https://github.com/chezou/julia-100-exercises).


## Neophyte

Import the numpy package under the name `np`


In [3]:
import numpy as np

Print the numpy version and the configuration.


In [5]:
print(np.__version__)
np.__config__.show()

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/soft/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/soft/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/soft/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/soft/Anaconda3\

Create a null vector of size 10


In [7]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a null vector of size 10 but the fifth value which is 1


In [8]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49


In [9]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Create a 3x3 matrix with values ranging from 0 to 8


In [10]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
np.nonzero(Z)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

Find indices of non-zero elements from [1,2,0,0,4,0]


In [13]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


Create a 3x3 identity matrix


In [15]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


In [16]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Create a 3x3x3 array with random values


In [17]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.12298536 0.1039869  0.94680769]
  [0.84687422 0.83741371 0.17039797]
  [0.55294336 0.74657134 0.38694042]]

 [[0.07464298 0.36727086 0.66955669]
  [0.10181483 0.88914599 0.17654713]
  [0.77478639 0.58334543 0.29009142]]

 [[0.91782818 0.96577716 0.3040824 ]
  [0.79311985 0.99757284 0.31148817]
  [0.23939567 0.04232413 0.28729586]]]


## Novice

Create a 8x8 matrix and fill it with a checkerboard pattern


In [18]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Create a 10x10 array with random values and find the minimum and maximum
values


In [19]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.013657255612912533 0.9967264454883382


Create a checkerboard 8x8 matrix using the tile function


In [20]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Normalize a 5x5 random matrix (between 0 and 1)


In [21]:
Z = np.random.random((5,5))
Zmax,Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.0592853  0.7014257  0.42828996 0.         0.81366833]
 [0.80257212 0.37500889 0.68405643 0.56140079 0.61278027]
 [0.74290468 0.00801234 0.12290254 0.69831288 0.87015193]
 [0.93407006 0.40141659 0.23874442 0.86727044 0.00380617]
 [0.94626999 0.8363916  1.         0.28392091 0.65515917]]


Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)


In [22]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Create a 5x5 matrix with row values ranging from 0 to 4


In [23]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Create a vector of size 10 with values ranging from 0 to 1, both
excluded


In [24]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Create a random vector of size 10 and sort it


In [25]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.07935263 0.2032601  0.24911796 0.35251913 0.39072096 0.42894726
 0.66744841 0.71492812 0.74697914 0.78727015]


Consider two random array A anb B, check if they are equal.


In [26]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


Create a random vector of size 30 and find the mean value


In [27]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5699680604892808


## Apprentice

Make an array immutable (read-only)


In [28]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

Consider a random 10x2 matrix representing cartesian coordinates,
convert them to polar coordinates


In [30]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.42404791 1.15233492 0.37677837 0.60607261 0.81291716 1.11965929
 0.74193769 0.95851352 0.24321096 0.40659022]
[1.49593418 0.84710739 1.32255831 0.62665428 0.67518798 0.49778214
 1.42864899 1.45561494 0.13078747 1.46873914]


Create random vector of size 10 and replace the maximum value by 0


In [31]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.83161618 0.33760136 0.83827486 0.81400591 0.         0.36869111
 0.02969678 0.82034485 0.551234   0.23958086]


Create a structured array with `x` and `y` coordinates covering the
[0,1]x[0,1] area.


In [32]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

Print the minimum and maximum representable value for each numpy scalar
type


In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print np.iinfo(dtype).min
   print np.iinfo(dtype).max
for dtype in [np.float32, np.float64]:
   print np.finfo(dtype).min
   print np.finfo(dtype).max
   print np.finfo(dtype).eps

Create a structured array representing a position (x,y) and a color
(r,g,b)


In [ ]:
 Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print Z

Consider a random vector with shape (100,2) representing coordinates,
find point by point distances


In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print D

# Much faster with scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print D

Generate a generic 2D Gaussian-like array


In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print G

How to tell if a given 2D array has null columns ?


In [ ]:
# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print (~Z.any(axis=0)).any()

Find the nearest value from a given value in an array


In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print m

## Journeyman

Consider the following file:


How to read it ?


In [ ]:
Z = np.genfromtxt("missing.dat", delimiter=",")

Consider a generator function that generates 10 integers and use it to
build an array


In [ ]:
def generate():
    for x in xrange(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print Z

Consider a given vector, how to add 1 to each element indexed by a
second vector (be careful with repeated indices) ?


In [ ]:
# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print Z

How to accumulate elements of a vector (X) to an array (F) based on an
index list (I) ?


In [ ]:
# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print F

Considering a (w,h,3) image of (dtype=ubyte), compute the number of
unique colors


In [ ]:
# Author: Nadav Horesh

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print np.unique(I)

Considering a four dimensions array, how to get sum over the last two
axis at once ?


In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print

Considering a one-dimensional vector D, how to compute means of subsets
of D using a vector S of same size describing subset indices ?


In [ ]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print D_means

Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3
consecutive zeros interleaved between each value ?


In [ ]:
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print Z0

Consider an array of dimension (5,5,3), how to mulitply it by an array
with dimensions (5,5) ?


In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print A * B[:,:,None]

How to swap two rows of an array ?


In [ ]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print A

## Craftsman

Consider a one-dimensional array Z, build a two-dimensional array whose
first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1
(last row should be (Z[-3],Z[-2],Z[-1])


In [ ]:
# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print Z

Consider a set of 10 triplets describing 10 triangles (with shared
vertices), find the set of unique line segments composing all the
triangles.


In [ ]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print G

Given an array C that is a bincount, how to produce an array A such that
np.bincount(A) == C ?


In [ ]:
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print A

How to compute averages using a sliding window over an array ?


In [ ]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print moving_average(Z, n=3)

## Artisan

Considering a 10x3 matrix, extract rows with unequal values (e.g.
[2,2,3])


In [ ]:
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print Z
print U

Convert a vector of ints into a matrix binary representation.


In [ ]:
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print B[:,::-1]

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print np.unpackbits(I[:, np.newaxis], axis=1)

## Adept

Consider an arbitrary array, write a function that extract a subpart
with a fixed shape and centered on a given element (pad with a `fill`
value when necessary)


Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to
generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,
[11,12,13,14]] ?


In [ ]:
# Author: Stéfan van der Walt

Z = np.arange(1,15,dtype=uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print R

## Expert

Consider two arrays A and B of shape (8,3) and (2,2). How to find rows
of A that contain elements of each row of B regardless of the order of
the elements in B ?


In [ ]:
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print rows

Extract all the contiguous 3x3 blocks from a random 10x10 matrix.


In [ ]:
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print C

Create a 2D array subclass such that Z[i,j] == Z[j,i]


In [ ]:
# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, (i,j), value):
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print S

Consider a set of p matrices wich shape (n,n) and a set of p vectors
with shape (n,1). How to compute the sum of of the p matrix products at
once ? (result has shape (n,1))


In [ ]:
# Author: Stéfan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print S

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

## Master

Given a two dimensional array, how to extract unique rows ?


## Note

See
[stackoverflow](http://stackoverflow.com/questions/16970982/find-unique-rows-in-numpy-array/)
for explanations.


In [ ]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print uZ

## Archmaster